const HomeProducts = [
    {
        id:1,
        Name : 'Product1',
        price : '26',
        image : 'images/product1.jpg',
        cat :  'jeans',
        type : 'new',
        desc : "A blue jean to add in your cupboard",
        rating : "3.0",
    },
    {
        id:2,
        Name : 'Product2',
        price : '70',
        image : 'images/product2.jpg',
        cat :  't-shirt',
        type : 'featured',
        desc : "A branded printed t-shirt for mens",
        rating : "4.5",
    },
    {
        id:3,
        Name : 'Product3',
        price : '92',
        image : 'images/product3.jpg',
        cat :  'shoes',
        type : 'new',
        desc : "Brand new Nike shoes with extra comfort",
        rating : "3.5",
    },
    {
        id:4,
        Name : 'Product4',
        price : '110',
        image : 'images/product4.jpg',
        cat :  't-shirt',
        type : 'featured',
        desc : "Plain black t-shirt for mens",
        rating : "4.0",
    },
    {
        id:5,
        Name : 'Product5',
        price : '96',
        image : 'images/product5.jpg',
        cat :  'jeans',
        type : 'top',
        desc : "A branded faded jeans extra styling",
        rating : "4.8",
    },
    {
        id:6,
        Name : 'Product6',
        price : '80',
        image : 'images/product6.jpg',
        cat :  'shoes',
        type : 'New',
        desc : "Sneakers with latest color design",
        rating : "5.0",
    },
    {
        id:7,
        Name : 'Product7',
        price : '76',
        image : 'images/product7.jpg',
        cat :  'shirt',
        type : 'top',
        desc : "A stylish printed cotton shirt",
        rating : "4.0",
    },
    {
        id:8,
        Name : 'Product8',
        price : '105',
        image : 'images/product8.jpg',
        cat :  'shoes',
        type : 'top',
        desc : "Sneakers with latest color design", 
        rating : "4.3",  
    },
    {
        id:9,
        Name : 'Product9',
        price : '97',
        image : 'images/product9.jpg',
        cat :  'top',
        type : 'new',
        desc : "Printed cotton top for girls",
        rating : "3.0",
    },   
    {
        id:10,
        Name : 'Product10',
        price : '90',
        image : 'images/product10.jpg',
        cat :  'shoes',
        type : 'top',
        desc : "Neon Nike shoes for smooth running",
        rating : "3.8",
    },
    {
        id:11,
        Name : 'Product11',
        price : '120',
        image : 'images/product11.jpg',
        cat :  'blazer',
        type : 'new',
        desc : "Branded blazer for girls",
        rating : "4.3",
    },
    {
        id:12,
        Name : 'Product12',
        price : '85',
        image : 'images/product12.jpg',
        cat :  'watch',
        type : 'featured',
        desc : 'Branded wrist watch',
        rating : "4.2",
    }
]

export default HomeProducts;